version: '3.7'

services:
    db:
        image: 'postgres:alpine'
        restart: 'no'
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - dbdata:/var/lib/postgresql/data
        ports:
            - 55432:5432

    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly yes
        restart: 'no'
        volumes:
            - redisdata:/data
        ports:
            - 56379:6379

volumes:
    dbdata:
        name: py-telegram-broker-db
    redisdata:
        name: py-telegram-broker-redis
