version: '3.7'

services:
    db:
        image: 'postgres:alpine'
        restart: always
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - db-mtgdealer:/var/lib/postgresql/data
        ports:
            - "45432:5432"
        networks:
            - mtgdealer-net
        deploy:
            restart_policy:
                condition: on-failure
    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly yes
        restart: always
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - redis-mtgdealer:/data
        ports:
            - "46379:6379"
        networks:
            - mtgdealer-net
        deploy:
            restart_policy:
                condition: on-failure
    bot:
        image: "mtgdealer:latest"
        build: .
        restart: always
        volumes:
            - ./vol:/vol
        networks:
            - mtgdealer-net
        depends_on:
            - db
            - redis
        deploy:
            restart_policy:
                condition: on-failure
        
networks:
    mtgdealer-net:

volumes:
    redis-mtgdealer:
    db-mtgdealer:
