version: '3.7'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: salesboard:latest
        restart: unless-stopped
        environment:
            - SALESBOARD_PROXY={'protocol':'socks5','ip':'116.203.53.174','port':'1008','username':'telegram','password':'telegram'}
            - SALESBOARD_TOKEN='1165605883:AAFLmgZFDbRNzmFmM_MTKfr7IqeTIB6ZSzU'
            - SALESBOARD_ADMIN=['119707338']
            - SALESBOARD_WEBHOOK={'host':'https://static.174.53.203.116.clients.your-server.de'}
        volumes:
            - ./data/vol:/vol
        networks:
            - network
        depends_on:
            - db
            - redis

    db:
        image: 'postgres:alpine'
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - ./data/db:/var/lib/postgresql/data
        networks:
            - network

    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly yes
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - ./data/redis:/data
        networks:
            - network

networks:
    network:

