version: '3.7'

services:
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: "localhost"

  redis:
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: "localhost"
