version: '3.7'

services:
    db:
        image: 'postgres:alpine'
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 45432:5432
        networks:
            - expose-network

    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly yes
        restart: unless-stopped
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
        volumes:
            - ./data/redis:/data
        ports:
            - 46379:6379
        networks:
            - expose-network

networks:
    expose-network:
